### ISSUE TITLE
why it needs java 18?

### ISSUE THREAD

**Issue by peow** [SpiritXIV/minceraft#54]
sincere curiosity

**Comment by SpiritXIV** [comment]
To be honest I have no clue why it needs Java 18. It could be cause of the advanced shit it doing, then again, i dont fully know. All I know is it will not work if its running Java 17 or Java 16.
Later though I'll try figuring out why and I'll push it back to 17.

**Comment by SpiritXIV** [comment]
The mod now works with java 17
